name: Integration Test Github
on:
  push:
    branches:
      - http
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: tickyuss/linkup
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
